# Generated by Django 2.2 on 2019-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField(max_length=5000)),
            ],
        ),
    ]
