# Generated by Django 2.2 on 2019-05-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
